config/routes.rb
Scoreboard::Application.routes.draw do
  resources :highscores

end

app/models/highscore.rb
class Highscore < ActiveRecord::Base
  validates :name, :presence => {:message => 'Name cannot be blank.'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/highscores_controller.rb
class HighscoresController < ApplicationController
  # GET /highscores
  # GET /highscores.json
  respond_to :json
  
  def index
    #@highscores = Highscore.find(:all, order: "score").reverse
    @highscores = Highscore.select('name, score').order('score DESC')
	respond_with @highscores
    #respond_to do |format|
    #  format.html # index.html.erb
    #  format.json { render json: @highscores }
    #end
  end

  # GET /highscores/1
  # GET /highscores/1.json
  def show
    @highscore = Highscore.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @highscore }
    end
  end

  # GET /highscores/new
  # GET /highscores/new.json
  def new
    @highscore = Highscore.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @highscore }
    end
  end

  # GET /highscores/1/edit
  def edit
    @highscore = Highscore.find(params[:id])
  end

  # POST /highscores
  # POST /highscores.json
  def create
    @highscore = Highscore.new(params[:highscore])

    respond_to do |format|
      if @highscore.save
        format.html { redirect_to @highscore, notice: 'Highscore was successfully created.' }
        format.json { render json: @highscore, status: :created, location: @highscore }
      else
        format.html { render action: "new" }
        format.json { render json: @highscore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /highscores/1
  # PUT /highscores/1.json
  def update
    @highscore = Highscore.find(params[:id])

    respond_to do |format|
      if @highscore.update_attributes(params[:highscore])
        format.html { redirect_to @highscore, notice: 'Highscore was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @highscore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /highscores/1
  # DELETE /highscores/1.json
  def destroy
    @highscore = Highscore.find(params[:id])
    @highscore.destroy

    respond_to do |format|
      format.html { redirect_to highscores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/highscores_helper.rb
module HighscoresHelper
end

app/views/highscores/_form.html.erb
<%= form_for(@highscore) do |f| %>
  <% if @highscore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@highscore.errors.count, "error") %> prohibited this highscore from being saved:</h2>

      <ul>
      <% @highscore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/highscores/edit.html.erb
<h1>Editing highscore</h1>

<%= render 'form' %>

<%= link_to 'Show', @highscore %> |
<%= link_to 'Back', highscores_path %>

app/views/highscores/index.html.erb
<h1>Listing highscores</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Score</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @highscores.each do |highscore| %>
  <tr>
    <td><%= highscore.name %></td>
    <td><%= highscore.score %></td>
    <td><%= link_to 'Show', highscore %></td>
    <td><%= link_to 'Edit', edit_highscore_path(highscore) %></td>
    <td><%= link_to 'Destroy', highscore, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Highscore', new_highscore_path %>

app/views/highscores/new.html.erb
<h1>New highscore</h1>

<%= render 'form' %>

<%= link_to 'Back', highscores_path %>

app/views/highscores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @highscore.name %>
</p>

<p>
  <b>Score:</b>
  <%= @highscore.score %>
</p>


<%= link_to 'Edit', edit_highscore_path(@highscore) %> |
<%= link_to 'Back', highscores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scoreboard</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>